export const TELEGRAM_HOME_HELP_CALLBACK = 'home:help'
export const TELEGRAM_HOME_MY_BILL_CALLBACK = 'home:my_bill'
export const TELEGRAM_HOME_STATUS_CALLBACK = 'home:status'
export const TELEGRAM_HOME_BALANCES_CALLBACK = 'home:balances'
export const TELEGRAM_HOME_SETUP_CALLBACK = 'home:setup'
export const TELEGRAM_HOME_FEEDBACK_CALLBACK = 'home:feedback'

export const TELEGRAM_HOME_CALLBACKS = [
  TELEGRAM_HOME_HELP_CALLBACK,
  TELEGRAM_HOME_MY_BILL_CALLBACK,
  TELEGRAM_HOME_STATUS_CALLBACK,
  TELEGRAM_HOME_BALANCES_CALLBACK,
  TELEGRAM_HOME_SETUP_CALLBACK,
  TELEGRAM_HOME_FEEDBACK_CALLBACK
] as const

export type TelegramHomeCallback = (typeof TELEGRAM_HOME_CALLBACKS)[number]
